### ISSUE TITLE
Fix testing with pypy [SF:patches:136]

### ISSUE THREAD

**Issue by chrisjsewell** [chrisjsewell/docutils#161]
author:   mathy
created:  2016-10-19 14:28:22.373000
assigned: None
SF_url:   https://sourceforge.net/p/docutils/patches/136

attachments:

  - https://sourceforge.net/p/docutils/patches/136/attachment/docutils-pypy.patch

Some of the tests are broken when using PyPy:
* The backport of the csv_eod_error_str never happened in pypy so I added an extra check for this
* The exception thrown when trying to parse a string as integer was outputting the u to identify it as a unicode string which did not match the expected output (see below). I added a u identifier to the string which solves it.

Example:
-             invalid literal for int() with base 10: 'fifty'.
+             invalid literal for int() with base 10: u'fifty'.

Tested with 
* python-2.7.10
* python-3.4.3
* python-3.5.2
* pypy-5.4.1
* pypy3-5.5.0_alpha

I don't have earlier python versions available for testing.

---
commenter: mathy
posted:    2016-10-19 14:29:04.314000
title:     #136 Fix testing with pypy

Sorry about the formatting, not used to this tracker ;-)

---
commenter: milde
posted:    2016-10-20 21:08:15.712000
title:     #136 Fix testing with pypy

The patch fails with Python 2.5:

~~~
Traceback (most recent call last):
  File "/home/milde/Code/Python/docutils-svn/docutils/test/alltests.py", line 79, in <module>
    suite = suite()
  File "/home/milde/Code/Python/docutils-svn/docutils/test/alltests.py", line 68, in suite
    'test_', packages=1)
  File "/home/milde/Code/Python/docutils-svn/docutils/test/package_unittest.py", line 101, in loadTestModules
    module = import_module(mod)
  File "/home/milde/Code/Python/docutils-svn/docutils/test/package_unittest.py", line 132, in import_module
    mod = __import__(name)
  File "/home/milde/Code/Python/docutils-svn/docutils/test/test_parsers/test_rst/test_directives/test_tables.py", line 40, in <module>
    platform.python_implementation() == 'PyPy' or not (
AttributeError: 'module' object has no attribute 'python_implementation'
~~~

---
commenter: milde
posted:    2016-11-29 12:13:09.634000
title:     #136 Fix testing with pypy

- **status**: open --> pending-remind

---
commenter: milde
posted:    2016-11-29 12:13:09.865000
title:     #136 Fix testing with pypy

A version of the patch that works with 2.5 and 2.4 is now in (rev. 7976).

Please test and close the ticket if OK.

---
commenter: milde
posted:    2017-02-03 16:06:22.470000
title:     #136 Fix testing with pypy

- **status**: pending-remind --> closed-fixed

---
commenter: milde
posted:    2017-02-03 16:06:22.738000
title:     #136 Fix testing with pypy

Closing now. Please reopen if there are remaining problems.

Thank you for report and patch.
